<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('schools', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('name'); $t->string('status')->default('ACTIVE'); $t->timestampsTz(); });
        Schema::create('terminals', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignUuid('school_id')->constrained('schools'); $t->string('name'); $t->string('status')->default('ACTIVE'); $t->string('protocol_version')->default('1'); $t->timestampsTz(); $t->index(['school_id','status']); });
        Schema::create('device_credentials', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignUuid('terminal_id')->constrained('terminals'); $t->string('token_hash', 64)->unique(); $t->string('status')->default('ACTIVE'); $t->timestampTz('rotated_at')->nullable(); $t->timestampTz('revoked_at')->nullable(); $t->timestampsTz(); $t->index(['terminal_id','status']); });
        Schema::create('terminal_enrollment_codes', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignUuid('school_id')->constrained('schools'); $t->string('code_hash'); $t->timestampTz('expires_at')->nullable(); $t->timestampTz('used_at')->nullable(); $t->integer('uses_remaining')->default(1); $t->timestampsTz(); $t->index(['school_id','used_at']); });
        Schema::create('classes', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignUuid('school_id')->constrained('schools'); $t->string('name'); $t->unsignedBigInteger('version')->default(1); $t->timestampTz('deleted_at')->nullable(); $t->timestampsTz(); $t->unique(['school_id','name']); });
        Schema::create('persons', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignUuid('school_id')->constrained('schools'); $t->uuid('class_id')->nullable(); $t->string('full_name'); $t->string('person_type'); $t->string('class_name')->nullable(); $t->string('position_name')->nullable(); $t->string('status')->default('ACTIVE'); $t->unsignedBigInteger('version')->default(1); $t->timestampTz('deleted_at')->nullable(); $t->timestampsTz(); $t->foreign('class_id')->references('id')->on('classes'); $t->index(['school_id','status']); });
        Schema::create('cards', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignUuid('school_id')->constrained('schools'); $t->foreignUuid('person_id')->constrained('persons'); $t->string('card_lookup_hash', 128); $t->string('status')->default('ACTIVE'); $t->unsignedBigInteger('version')->default(1); $t->timestampsTz(); $t->unique(['school_id','card_lookup_hash']); $t->index(['person_id','status']); });
        Schema::create('face_templates', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignUuid('school_id')->constrained('schools'); $t->foreignUuid('person_id')->constrained('persons'); $t->text('template_ciphertext'); $t->string('model_id'); $t->string('model_version'); $t->unsignedBigInteger('template_version'); $t->string('consent_reference')->nullable(); $t->string('consent_status')->default('ACTIVE'); $t->timestampTz('enrolled_at'); $t->timestampTz('revoked_at')->nullable(); $t->timestampsTz(); $t->index(['school_id','consent_status']); });
        Schema::create('library_locations', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignUuid('school_id')->constrained('schools'); $t->string('name'); $t->string('code'); $t->unsignedBigInteger('version')->default(1); $t->timestampTz('deleted_at')->nullable(); $t->timestampsTz(); $t->unique(['school_id','code']); });
        Schema::create('book_titles', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignUuid('school_id')->constrained('schools'); $t->string('isbn')->nullable(); $t->string('title'); $t->string('authors'); $t->string('language'); $t->string('publisher')->nullable(); $t->integer('publication_year')->nullable(); $t->string('subject')->nullable(); $t->string('grade')->nullable(); $t->unsignedBigInteger('version')->default(1); $t->timestampTz('deleted_at')->nullable(); $t->timestampsTz(); $t->index(['school_id','isbn']); $t->index(['school_id','title']); });
        Schema::create('book_copies', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignUuid('school_id')->constrained('schools'); $t->foreignUuid('book_title_id')->constrained('book_titles'); $t->uuid('location_id')->nullable(); $t->string('inventory_number')->nullable(); $t->string('barcode')->nullable(); $t->string('status')->default('AVAILABLE'); $t->unsignedBigInteger('version')->default(1); $t->timestampTz('deleted_at')->nullable(); $t->timestampsTz(); $t->foreign('location_id')->references('id')->on('library_locations'); $t->unique(['school_id','inventory_number']); $t->unique(['school_id','barcode']); $t->index(['school_id','status']); });
        Schema::create('legacy_title_stock', function (Blueprint $t) { $t->uuid('book_title_id')->primary(); $t->foreignUuid('school_id')->constrained('schools'); $t->integer('total_quantity'); $t->integer('available_quantity'); $t->unsignedBigInteger('version')->default(1); $t->timestampsTz(); });
        Schema::create('loans', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignUuid('school_id')->constrained('schools'); $t->foreignUuid('reader_id')->constrained('persons'); $t->foreignUuid('book_title_id')->constrained('book_titles'); $t->uuid('book_copy_id')->nullable(); $t->string('accounting_mode'); $t->integer('quantity'); $t->integer('returned_quantity')->default(0); $t->timestampTz('issued_at'); $t->timestampTz('due_at')->nullable(); $t->timestampTz('returned_at')->nullable(); $t->string('status')->default('ACTIVE'); $t->foreignUuid('created_terminal_id')->constrained('terminals'); $t->unsignedBigInteger('version')->default(1); $t->timestampsTz(); $t->foreign('book_copy_id')->references('id')->on('book_copies'); $t->index(['school_id','reader_id','status']); });
        DB::statement("ALTER TABLE legacy_title_stock ADD CONSTRAINT legacy_stock_quantity_check CHECK (total_quantity >= 0 AND available_quantity >= 0 AND available_quantity <= total_quantity)");
        DB::statement("ALTER TABLE loans ADD CONSTRAINT loan_accounting_check CHECK ((accounting_mode = 'COPY' AND book_copy_id IS NOT NULL AND quantity = 1) OR (accounting_mode = 'LEGACY_TITLE' AND book_copy_id IS NULL AND quantity > 0))");
        DB::statement("CREATE UNIQUE INDEX loans_active_copy_unique ON loans (book_copy_id) WHERE status = 'ACTIVE' AND book_copy_id IS NOT NULL");
        Schema::create('reservations', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignUuid('school_id')->constrained('schools'); $t->foreignUuid('reader_id')->constrained('persons'); $t->foreignUuid('book_title_id')->constrained('book_titles'); $t->string('status')->default('WAITING'); $t->unsignedBigInteger('version')->default(1); $t->timestampsTz(); $t->index(['school_id','book_title_id','status','created_at']); });
        DB::statement("CREATE UNIQUE INDEX reservations_waiting_unique ON reservations (reader_id, book_title_id) WHERE status = 'WAITING'");
        Schema::create('terminal_operations', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignUuid('school_id')->constrained('schools'); $t->foreignUuid('terminal_id')->constrained('terminals'); $t->uuid('operation_id')->unique(); $t->string('operation_type'); $t->timestampTz('occurred_at'); $t->timestampTz('received_at'); $t->string('payload_hash', 64); $t->jsonb('payload'); $t->jsonb('result'); $t->string('status'); $t->timestampsTz(); $t->index(['school_id','terminal_id','received_at']); });
        Schema::create('idempotency_receipts', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignUuid('school_id')->constrained('schools'); $t->foreignUuid('terminal_id')->constrained('terminals'); $t->uuid('operation_id')->unique(); $t->string('payload_hash',64); $t->jsonb('result'); $t->timestampTz('received_at'); $t->timestampsTz(); });
        Schema::create('sync_changes', function (Blueprint $t) { $t->bigIncrements('sequence'); $t->foreignUuid('school_id')->constrained('schools'); $t->string('entity_type'); $t->uuid('entity_id'); $t->unsignedBigInteger('version'); $t->string('operation'); $t->jsonb('payload')->nullable(); $t->timestampTz('created_at'); $t->index(['school_id','sequence']); });
        Schema::create('device_sync_state', function (Blueprint $t) { $t->foreignUuid('terminal_id')->primary()->constrained('terminals'); $t->foreignUuid('school_id')->constrained('schools'); $t->unsignedBigInteger('last_pull_sequence')->default(0); $t->timestampTz('last_sync_at')->nullable(); $t->timestampsTz(); });
        Schema::create('audit_log', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignUuid('school_id')->constrained('schools'); $t->uuid('terminal_id')->nullable(); $t->uuid('operation_id')->nullable(); $t->string('actor')->nullable(); $t->string('action'); $t->uuid('reader_id')->nullable(); $t->uuid('book_title_id')->nullable(); $t->uuid('book_copy_id')->nullable(); $t->timestampTz('occurred_at'); $t->timestampTz('received_at'); $t->string('result'); $t->string('error_code')->nullable(); $t->timestampsTz(); $t->index(['school_id','received_at']); });
    }
    public function down(): void { foreach (['audit_log','device_sync_state','sync_changes','idempotency_receipts','terminal_operations','reservations','loans','legacy_title_stock','book_copies','book_titles','library_locations','face_templates','cards','persons','classes','terminal_enrollment_codes','device_credentials','terminals','schools'] as $table) Schema::dropIfExists($table); }
};

